version: ~> 1.0

env:
  global:
    # doctr generated secure variable for documentation upload
    # - secure: "<your secure here>"
    
    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="lucid"

    # The name of the conda package
    - CONDA_PACKAGE="lucid"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # in the recipe or CONDA_REQUIREMENTS. E.g. PyQt
    - CONDA_EXTRAS="pip pyqt=5 happi"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="PyQt5 happi"

# jobs:
#   allow_failures:
#     # This makes the PIP based Python 3.6 optional for passing.
#     # Remove this block if passing tests with PIP is mandatory for your
#     # package
#     - name: "Python 3.6 - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
