version: ~> 1.0

env:
  global:
    # doctr generated secure variable for documentation upload
    - secure: "XwyA3nWBR1rKUZ1t3c5R93DPwBiT1eSiUw1RoMtnRoDm3qrPRdLUkseXtefk3FAxeWT3Wkt8eLqIyhmWIu4CNfz1w72XvbzFQ2TJYooCDvoD2MIMSD0v3KfejAq9flsc9l+7K4ZXSo8NZjYy2I7mewIERhiBS7CBXPZ4FBFb2iJQgyX/Ygu+XrqRLoEjePxBOPVrCXlBpmrE5SGJlRscA57Y6RBbREBJnUEaaJhSljvyz5A9TDae+Rz0RVoI8eR+g1fdrT1gm84y8HUD4O99K7g17O9vivSR0YcN+/Yu9mJfVEAkh0kQeK4MBF1d35l8Mf1M8/+LvFgODE2lRhDNA6SNbLsIRs8qmCX0wH22sxwcNeIMGHjhK8AuIX7JYCSOuMH2+sEKOkQ3DomybJx2+QqgW/gxtpU6ZSKAnzQHk48NvQnDgME9BM9UH/016ZS5FC4iYwCa2wiO6meCN/ljUCtIH4UqmR+vv/GcMwmAVm5rLaRytTXDTUCHsODMU5635ddikz+daXgbUbe00nY9Pnzdx7tl271oGzQl9oq1E6Q5djtyqUObO1+TMz0ZU+fbj51F2MKyxdHxF2h85BRjXHKk116mLJoc4VwZxtUYxxu0Gh4XxH+CE+R+3sVgdqjebuE4ElvPxufdL4CjL7wQx0WNAXW1/tXInR6r+S4AcBQ="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"

    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="docs-requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="lucid"

    # The name of the conda package
    - CONDA_PACKAGE="lucid"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # in the recipe or CONDA_REQUIREMENTS. E.g. PyQt
    - CONDA_EXTRAS="pip pyqt=5 happi"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS="PyQt5 happi"

jobs:
  allow_failures:
    # ** pyqtads is not available on PyPI, so this cannot succeed:
    - name: "Python 3.8 - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  # This import enables a set of standard python jobs including:
  # - Build
  #   - Anaconda Package Build
  # - Tests
  #   - Linter
  #   - Documentation
  #   - Python 3.6 - PIP based
  #   - Python 3.6, 3.7 & 3.8 - Conda base
  # - Deploy
  #   - Documentation using doctr
  #   - Conda Package - uploaded to pcds-dev and pcds-tag
  #   - PyPI
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda.yml
