dist: xenial
language: python
sudo: false

services:
  - xvfb

addons:
  apt:
    packages:
      - herbstluftwm
      - libxkbcommon-x11-0

env:
  global:
    - OFFICIAL_REPO="slaclab/lucid"

matrix:
  include:
    - name: flake8 linting
      python: 3.6
      env: LINT_PYTHON=lucid
    - python: 3.6
#      env: BUILD_DOCS=0
    - python: 3.7

install:
  - git clone --depth 1 git://github.com/pcdshub/pcds-ci-helpers.git
  - source pcds-ci-helpers/travis/init.sh
 
  # Install, configure conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  - conda config --remove channels defaults
  - conda config --add channels conda-forge
  # Useful for debugging
  - conda info -a
  - conda build -q conda-recipe --python $TRAVIS_PYTHON_VERSION --output-folder bld-dir
  - conda config --add channels "file://`pwd`/bld-dir"
  # Manage conda environment
  - conda create -n lucid-env python=$TRAVIS_PYTHON_VERSION lucid pip pyqt --file dev-requirements.txt
  - source activate lucid-env
  # Useful for debugging
  - conda list

before_script:
  # Run windows manager
  - "herbstluftwm &"
  - sleep 1

script:
  - coverage run run_tests.py
  - coverage report -m
  - set -e
  - |
    if [[ $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $BUILD_DOCS ]]; then
      pushd docs
      make html
      popd
      doctr deploy . --built-docs docs/_build/html --deploy-branch-name gh-pages --command "touch .nojekyll; git add .nojekyll"
    fi
after_success:
  - codecov
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_TAG
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      anaconda upload bld-dir/linux-64/*.tar.bz2
    fi
